/*
 * I2C_preprocessor_macros.h
 *
 *  Created on: Apr 18, 2020
 *      Author: pokas
 */

#ifndef _MICROHAL_PORTS_STMCOMMON_I2C_PREPROCESSOR_MACROS_H_
#define _MICROHAL_PORTS_STMCOMMON_I2C_PREPROCESSOR_MACROS_H_

#include "../stmCommonDefines.h"
#include _MICROHAL_INCLUDE_PORT_CONFIG

#ifndef MICROHAL_USE_I2C1_POLLING
#define MICROHAL_USE_I2C1_POLLING 0
#endif

#ifndef MICROHAL_USE_I2C2_POLLING
#define MICROHAL_USE_I2C2_POLLING 0
#endif

#ifndef MICROHAL_USE_I2C3_POLLING
#define MICROHAL_USE_I2C3_POLLING 0
#endif

#ifndef MICROHAL_USE_I2C4_POLLING
#define MICROHAL_USE_I2C4_POLLING 0
#endif

#ifndef MICROHAL_USE_I2C5_POLLING
#define MICROHAL_USE_I2C5_POLLING 0
#endif

#ifndef MICROHAL_USE_I2C6_POLLING
#define MICROHAL_USE_I2C6_POLLING 0
#endif

#ifndef MICROHAL_USE_I2C7_POLLING
#define MICROHAL_USE_I2C7_POLLING 0
#endif

#ifndef MICROHAL_USE_I2C1_INTERRUPT
#define MICROHAL_USE_I2C1_INTERRUPT 0
#endif

#ifndef MICROHAL_USE_I2C2_INTERRUPT
#define MICROHAL_USE_I2C2_INTERRUPT 0
#endif

#ifndef MICROHAL_USE_I2C3_INTERRUPT
#define MICROHAL_USE_I2C3_INTERRUPT 0
#endif

#ifndef MICROHAL_USE_I2C4_INTERRUPT
#define MICROHAL_USE_I2C4_INTERRUPT 0
#endif

#ifndef MICROHAL_USE_I2C5_INTERRUPT
#define MICROHAL_USE_I2C5_INTERRUPT 0
#endif

#ifndef MICROHAL_USE_I2C6_INTERRUPT
#define MICROHAL_USE_I2C6_INTERRUPT 0
#endif

#ifndef MICROHAL_USE_I2C7_INTERRUPT
#define MICROHAL_USE_I2C7_INTERRUPT 0
#endif

#ifndef MICROHAL_USE_I2C1_DMA
#define MICROHAL_USE_I2C1_DMA 0
#endif

#ifndef MICROHAL_USE_I2C2_DMA
#define MICROHAL_USE_I2C2_DMA 0
#endif

#ifndef MICROHAL_USE_I2C3_DMA
#define MICROHAL_USE_I2C3_DMA 0
#endif

#ifndef MICROHAL_USE_I2C4_DMA
#define MICROHAL_USE_I2C4_DMA 0
#endif

#ifndef MICROHAL_USE_I2C5_DMA
#define MICROHAL_USE_I2C5_DMA 0
#endif

#ifndef MICROHAL_USE_I2C6_DMA
#define MICROHAL_USE_I2C6_DMA 0
#endif

#ifndef MICROHAL_USE_I2C7_DMA
#define MICROHAL_USE_I2C7_DMA 0
#endif

#define ENABLED_ANY_I2C(x)                                                                                                   \
    (MICROHAL_USE_I2C1_##x == 1 || MICROHAL_USE_I2C2_##x == 1 || MICROHAL_USE_I2C3_##x == 1 || MICROHAL_USE_I2C4_##x == 1 || \
     MICROHAL_USE_I2C5_##x == 1 || MICROHAL_USE_I2C6_##x == 1 || MICROHAL_USE_I2C7_##x == 1)

#endif /* _MICROHAL_PORTS_STMCOMMON_I2C_PREPROCESSOR_MACROS_H_ */
