/*
 * serialPort_preprocessor_macros.h
 *
 *  Created on: Apr 19, 2020
 *      Author: pokas
 */

#ifndef _MICROHAL_PORTS_STMCOMMON_SERIALPORT_V1_SERIALPORT_PREPROCESSOR_MACROS_H_
#define _MICROHAL_PORTS_STMCOMMON_SERIALPORT_V1_SERIALPORT_PREPROCESSOR_MACROS_H_

#include "../stmCommonDefines.h"
#include _MICROHAL_INCLUDE_PORT_CONFIG

#ifndef MICROHAL_USE_SERIAL_PORT1_POLLING
#define MICROHAL_USE_SERIAL_PORT1_POLLING 0
#endif

#ifndef MICROHAL_USE_SERIAL_PORT2_POLLING
#define MICROHAL_USE_SERIAL_PORT2_POLLING 0
#endif

#ifndef MICROHAL_USE_SERIAL_PORT3_POLLING
#define MICROHAL_USE_SERIAL_PORT3_POLLING 0
#endif

#ifndef MICROHAL_USE_SERIAL_PORT4_POLLING
#define MICROHAL_USE_SERIAL_PORT4_POLLING 0
#endif

#ifndef MICROHAL_USE_SERIAL_PORT5_POLLING
#define MICROHAL_USE_SERIAL_PORT5_POLLING 0
#endif

#ifndef MICROHAL_USE_SERIAL_PORT6_POLLING
#define MICROHAL_USE_SERIAL_PORT6_POLLING 0
#endif

#ifndef MICROHAL_USE_SERIAL_PORT7_POLLING
#define MICROHAL_USE_SERIAL_PORT7_POLLING 0
#endif

#ifndef MICROHAL_USE_SERIAL_PORT8_POLLING
#define MICROHAL_USE_SERIAL_PORT8_POLLING 0
#endif

#ifndef MICROHAL_USE_SERIAL_PORT1_INTERRUPT
#define MICROHAL_USE_SERIAL_PORT1_INTERRUPT 0
#endif

#ifndef MICROHAL_USE_SERIAL_PORT2_INTERRUPT
#define MICROHAL_USE_SERIAL_PORT2_INTERRUPT 0
#endif

#ifndef MICROHAL_USE_SERIAL_PORT3_INTERRUPT
#define MICROHAL_USE_SERIAL_PORT3_INTERRUPT 0
#endif

#ifndef MICROHAL_USE_SERIAL_PORT4_INTERRUPT
#define MICROHAL_USE_SERIAL_PORT4_INTERRUPT 0
#endif

#ifndef MICROHAL_USE_SERIAL_PORT5_INTERRUPT
#define MICROHAL_USE_SERIAL_PORT5_INTERRUPT 0
#endif

#ifndef MICROHAL_USE_SERIAL_PORT6_INTERRUPT
#define MICROHAL_USE_SERIAL_PORT6_INTERRUPT 0
#endif

#ifndef MICROHAL_USE_SERIAL_PORT7_INTERRUPT
#define MICROHAL_USE_SERIAL_PORT7_INTERRUPT 0
#endif

#ifndef MICROHAL_USE_SERIAL_PORT8_INTERRUPT
#define MICROHAL_USE_SERIAL_PORT8_INTERRUPT 0
#endif

#ifndef MICROHAL_USE_SERIAL_PORT1_DMA
#define MICROHAL_USE_SERIAL_PORT1_DMA 0
#endif

#ifndef MICROHAL_USE_SERIAL_PORT2_DMA
#define MICROHAL_USE_SERIAL_PORT2_DMA 0
#endif

#ifndef MICROHAL_USE_SERIAL_PORT3_DMA
#define MICROHAL_USE_SERIAL_PORT3_DMA 0
#endif

#ifndef MICROHAL_USE_SERIAL_PORT4_DMA
#define MICROHAL_USE_SERIAL_PORT4_DMA 0
#endif

#ifndef MICROHAL_USE_SERIAL_PORT5_DMA
#define MICROHAL_USE_SERIAL_PORT5_DMA 0
#endif

#ifndef MICROHAL_USE_SERIAL_PORT6_DMA
#define MICROHAL_USE_SERIAL_PORT6_DMA 0
#endif

#ifndef MICROHAL_USE_SERIAL_PORT7_DMA
#define MICROHAL_USE_SERIAL_PORT7_DMA 0
#endif

#ifndef MICROHAL_USE_SERIAL_PORT8_DMA
#define MICROHAL_USE_SERIAL_PORT8_DMA 0
#endif

#define ENABLED_ANY_SERIAL_PORT(x)                                                                                     \
    (MICROHAL_USE_SERIAL_PORT1_##x == 1 || MICROHAL_USE_SERIAL_PORT2_##x == 1 || MICROHAL_USE_SERIAL_PORT3_##x == 1 || \
     MICROHAL_USE_SERIAL_PORT4_##x == 1 || MICROHAL_USE_SERIAL_PORT5_##x == 1 || MICROHAL_USE_SERIAL_PORT6_##x == 1 || \
     MICROHAL_USE_SERIAL_PORT7_##x == 1 || MICROHAL_USE_SERIAL_PORT8_##x == 1)

#endif /* _MICROHAL_PORTS_STMCOMMON_SERIALPORT_V1_SERIALPORT_PREPROCESSOR_MACROS_H_ */
