#ifndef _MICROHAL_PORTS_STM32F4XX_DRIVER_CONFIGURATION_STM32F4XX_H_
#define _MICROHAL_PORTS_STM32F4XX_DRIVER_CONFIGURATION_STM32F4XX_H_

//#define _MICROHAL_PORT_STM_ADC_DRIVER_VERSION 1
#define _MICROHAL_PORT_STM_GPIO_DRIVER_VERSION 1
#if defined(STM32F407xx) || defined(STM32F411xE) || defined(STM32F412) || defined(STM32F401) || defined(STM32F405) || defined(STM32F410) || \
    defined(STM32F429) || defined(STM32F469) || defined(STM32F427) || defined(STM32F446) || defined(STM32F413)
#define _MICROHAL_PORT_STM_I2C_DRIVER_VERSION 1
#else
#define _MICROHAL_PORT_STM_I2C_DRIVER_VERSION 2
#endif
#define _MICROHAL_PORT_STM_CLOCK_MANAGER_PLL_DRIVER_VERSION 2
#define _MICROHAL_PORT_STM_INDEPENDENT_WATCHDOG_DRIVER_VERSION 1
#define _MICROHAL_PORT_STM_SERIAL_PORT_DRIVER_VERSION 1
#define _MICROHAL_PORT_STM_SPI_DRIVER_VERSION 1
#define _MICROHAL_PORT_STM_WINDOW_WATCHDOG_DRIVER_VERSION 1

#endif /* _MICROHAL_PORTS_STM32F4XX_DRIVER_CONFIGURATION_STM32F4XX_H_ */
