/*
 * driver_configuration_stm32f1xx.h
 *
 *  Created on: Apr 15, 2020
 *      Author: pokas
 */

#ifndef SRC_MICROHAL_PORTS_STM32F1XX_DRIVER_CONFIGURATION_STM32F1XX_H_
#define SRC_MICROHAL_PORTS_STM32F1XX_DRIVER_CONFIGURATION_STM32F1XX_H_

#define _MICROHAL_PORT_STM_ADC_DRIVER_VERSION 2
#define _MICROHAL_PORT_STM_CLOCK_MANAGER_PLL_DRIVER_VERSION 1
#define _MICROHAL_PORT_STM_DMA_DRIVER_VERSION 1
#define _MICROHAL_PORT_STM_GPIO_DRIVER_VERSION 2
#define _MICROHAL_PORT_STM_I2C_DRIVER_VERSION 1
#define _MICROHAL_PORT_STM_INDEPENDENT_WATCHDOG_DRIVER_VERSION 1
#define _MICROHAL_PORT_STM_SERIAL_PORT_DRIVER_VERSION 1
#define _MICROHAL_PORT_STM_SPI_DRIVER_VERSION 1
#define _MICROHAL_PORT_STM_WINDOW_WATCHDOG_DRIVER_VERSION 1

#endif /* SRC_MICROHAL_PORTS_STM32F1XX_DRIVER_CONFIGURATION_STM32F1XX_H_ */
