/*
 * spi_preprocessor_macros.h
 *
 *  Created on: Apr 18, 2020
 *      Author: pokas
 */

#ifndef _MICROHAL_PORTS_STMCOMMON_SPI_V1_SPI_PREPROCESSOR_MACROS_H_
#define _MICROHAL_PORTS_STMCOMMON_SPI_V1_SPI_PREPROCESSOR_MACROS_H_

#include "../stmCommonDefines.h"
#include _MICROHAL_INCLUDE_PORT_CONFIG

#ifndef MICROHAL_USE_SPI1_POLLING
#define MICROHAL_USE_SPI1_POLLING 0
#endif

#ifndef MICROHAL_USE_SPI2_POLLING
#define MICROHAL_USE_SPI2_POLLING 0
#endif

#ifndef MICROHAL_USE_SPI3_POLLING
#define MICROHAL_USE_SPI3_POLLING 0
#endif

#ifndef MICROHAL_USE_SPI4_POLLING
#define MICROHAL_USE_SPI4_POLLING 0
#endif

#ifndef MICROHAL_USE_SPI5_POLLING
#define MICROHAL_USE_SPI5_POLLING 0
#endif

#ifndef MICROHAL_USE_SPI6_POLLING
#define MICROHAL_USE_SPI6_POLLING 0
#endif

#ifndef MICROHAL_USE_SPI7_POLLING
#define MICROHAL_USE_SPI7_POLLING 0
#endif

#ifndef MICROHAL_USE_SPI1_INTERRUPT
#define MICROHAL_USE_SPI1_INTERRUPT 0
#endif

#ifndef MICROHAL_USE_SPI2_INTERRUPT
#define MICROHAL_USE_SPI2_INTERRUPT 0
#endif

#ifndef MICROHAL_USE_SPI3_INTERRUPT
#define MICROHAL_USE_SPI3_INTERRUPT 0
#endif

#ifndef MICROHAL_USE_SPI4_INTERRUPT
#define MICROHAL_USE_SPI4_INTERRUPT 0
#endif

#ifndef MICROHAL_USE_SPI5_INTERRUPT
#define MICROHAL_USE_SPI5_INTERRUPT 0
#endif

#ifndef MICROHAL_USE_SPI6_INTERRUPT
#define MICROHAL_USE_SPI6_INTERRUPT 0
#endif

#ifndef MICROHAL_USE_SPI7_INTERRUPT
#define MICROHAL_USE_SPI7_INTERRUPT 0
#endif

#ifndef MICROHAL_USE_SPI1_DMA
#define MICROHAL_USE_SPI1_DMA 0
#endif

#ifndef MICROHAL_USE_SPI2_DMA
#define MICROHAL_USE_SPI2_DMA 0
#endif

#ifndef MICROHAL_USE_SPI3_DMA
#define MICROHAL_USE_SPI3_DMA 0
#endif

#ifndef MICROHAL_USE_SPI4_DMA
#define MICROHAL_USE_SPI4_DMA 0
#endif

#ifndef MICROHAL_USE_SPI5_DMA
#define MICROHAL_USE_SPI5_DMA 0
#endif

#ifndef MICROHAL_USE_SPI6_DMA
#define MICROHAL_USE_SPI6_DMA 0
#endif

#ifndef MICROHAL_USE_SPI7_DMA
#define MICROHAL_USE_SPI7_DMA 0
#endif

#define ENABLED_ANY_SPI(x)                                                                                                   \
    (MICROHAL_USE_SPI1_##x == 1 || MICROHAL_USE_SPI2_##x == 1 || MICROHAL_USE_SPI3_##x == 1 || MICROHAL_USE_SPI4_##x == 1 || \
     MICROHAL_USE_SPI5_##x == 1 || MICROHAL_USE_SPI6_##x == 1 || MICROHAL_USE_SPI7_##x == 1)

#endif /* SRC_THIRD_PARTY_MICROHAL_PORTS_STMCOMMON_SPI_V1_SPI_PREPROCESSOR_MACROS_H_ */
